import type { AnalysisResponse } from "./types";

/**
 * Pre-generated analysis data from the Rust backend for the sample Python code.
 * Used in demo mode so the frontend works standalone without a live API.
 */
export const MOCK_RESPONSE: AnalysisResponse = {
  language: "python",
  execution: {
    instructions: [
      { op: "CALL", detail: "call increment(n)", cycles: 100 },
      { op: "LOAD", detail: "load param n", cycles: 1 },
      { op: "STORE", detail: "store return of increment", cycles: 1 },
      { op: "CALL", detail: "call fast_sum(data)", cycles: 100 },
      { op: "LOAD", detail: "load param data", cycles: 1 },
      { op: "STORE", detail: "store return of fast_sum", cycles: 1 },
      { op: "LOOP_START", detail: "for loop ~100 iterations (lines 9-14)", cycles: 8 },
      { op: "ADD", detail: "body statement x100", cycles: 700 },
      { op: "ADD", detail: "body statement x100", cycles: 700 },
      { op: "ADD", detail: "body statement x100", cycles: 700 },
      { op: "ADD", detail: "body statement x100", cycles: 700 },
      { op: "ADD", detail: "body statement x100", cycles: 700 },
      { op: "CMP", detail: "loop condition x100", cycles: 500 },
      { op: "LOOP_END", detail: "end for loop", cycles: 0 },
      { op: "LOOP_START", detail: "for loop ~100 iterations (lines 19-20)", cycles: 8 },
      { op: "ADD", detail: "body statement x100", cycles: 700 },
      { op: "CMP", detail: "loop condition x100", cycles: 500 },
      { op: "LOOP_END", detail: "end for loop", cycles: 0 },
      { op: "ALLOC", detail: "allocate str (Heap) \u2014 string of ~19 chars", cycles: 20 },
      { op: "ALLOC", detail: "allocate list_comprehension (Heap) \u2014 list comprehension (size depends on input)", cycles: 20 },
    ],
    maxCycles: 5460,
    summary: "20 pseudo-instructions, 5460 estimated cycles (2 functions, 2 loops, 2 allocations)",
  },
  cost: {
    lines: [
      { line: 7, cost: 50, label: "~50 cycles" },
      { line: 9, cost: 8, label: "~8 cycles" },
      { line: 10, cost: 500, label: "~500 cycles" },
      { line: 11, cost: 500, label: "~500 cycles" },
      { line: 12, cost: 500, label: "~500 cycles" },
      { line: 13, cost: 500, label: "~500 cycles" },
      { line: 14, cost: 500, label: "~500 cycles" },
      { line: 16, cost: 50, label: "~50 cycles" },
      { line: 17, cost: 20, label: "~20 cycles" },
      { line: 19, cost: 8, label: "~8 cycles" },
      { line: 20, cost: 500, label: "~500 cycles" },
      { line: 29, cost: 20, label: "~20 cycles" },
    ],
    maxCost: 500,
    insights: "Line 20 is the hottest at ~500 estimated cycles. 2 function(s), 2 loop(s), 2 allocation(s) contribute to the total cost.",
  },
  memory: {
    allocations: [
      { type: "heap", name: "str", detail: "string of ~19 chars", size: "~68 B" },
      { type: "heap", name: "list_comprehension", detail: "list comprehension (size depends on input)", size: "~dynamic B" },
    ],
    stackTotal: "0 B",
    heapTotal: "68 B",
    allocCount: 2,
    notes: "2 heap allocations totaling ~68 B Largest: string of ~19 chars (~68 B).",
  },
  concurrency: {
    threads: [
      {
        name: "main",
        events: [
          { type: "lock", label: "lock lock" },
          { type: "unlock", label: "unlock lock" },
          { type: "write", label: "write counter" },
          { type: "spawn", label: "thread_spawn: threading.Thread(target=increment, args=(100,))" },
          { type: "spawn", label: "thread_spawn: threading.Thread(target=increment, args=(100,))" },
        ],
      },
      {
        name: "thread-0",
        events: [
          { type: "spawn", label: "threading.Thread(target=increment, args=(100,))" },
        ],
      },
      {
        name: "thread-1",
        events: [
          { type: "spawn", label: "threading.Thread(target=increment, args=(100,))" },
        ],
      },
    ],
    warnings: ["1 shared variable access(es) outside locked regions"],
    analysis: "1 potential issue(s) found. Review warnings.",
  },
  assembly: {
    arch: "cpython-bytecode",
    blocks: [
      {
        label: "module",
        instructions: [
          { addr: "0", op: "RESUME", operands: "0", comment: "" },
          { addr: "2", op: "LOAD_CONST", operands: "0 (0)", comment: "" },
          { addr: "4", op: "LOAD_CONST", operands: "1 (None)", comment: "" },
          { addr: "6", op: "IMPORT_NAME", operands: "0 (threading)", comment: "" },
          { addr: "8", op: "STORE_NAME", operands: "0 (threading)", comment: "" },
          { addr: "10", op: "LOAD_CONST", operands: "0 (0)", comment: "" },
          { addr: "12", op: "LOAD_CONST", operands: "1 (None)", comment: "" },
          { addr: "14", op: "IMPORT_NAME", operands: "1 (time)", comment: "" },
          { addr: "16", op: "STORE_NAME", operands: "1 (time)", comment: "" },
          { addr: "18", op: "LOAD_CONST", operands: "0 (0)", comment: "" },
          { addr: "20", op: "STORE_GLOBAL", operands: "2 (counter)", comment: "" },
          { addr: "22", op: "PUSH_NULL", operands: "", comment: "" },
          { addr: "24", op: "LOAD_NAME", operands: "0 (threading)", comment: "" },
          { addr: "26", op: "LOAD_ATTR", operands: "6 (Lock)", comment: "" },
          { addr: "46", op: "CALL", operands: "0", comment: "" },
          { addr: "54", op: "STORE_NAME", operands: "4 (lock)", comment: "" },
          { addr: "56", op: "LOAD_CONST", operands: "2 (<code object increment>)", comment: "" },
          { addr: "58", op: "MAKE_FUNCTION", operands: "0", comment: "" },
          { addr: "60", op: "STORE_NAME", operands: "5 (increment)", comment: "" },
          { addr: "62", op: "LOAD_CONST", operands: "3 (<code object fast_sum>)", comment: "" },
          { addr: "64", op: "MAKE_FUNCTION", operands: "0", comment: "" },
          { addr: "66", op: "STORE_NAME", operands: "6 (fast_sum)", comment: "" },
          { addr: "68", op: "PUSH_NULL", operands: "", comment: "" },
          { addr: "70", op: "LOAD_NAME", operands: "0 (threading)", comment: "" },
          { addr: "72", op: "LOAD_ATTR", operands: "14 (Thread)", comment: "" },
          { addr: "92", op: "LOAD_NAME", operands: "5 (increment)", comment: "" },
          { addr: "94", op: "LOAD_CONST", operands: "4 ((100,))", comment: "" },
          { addr: "96", op: "KW_NAMES", operands: "5 (('target', 'args'))", comment: "" },
          { addr: "98", op: "CALL", operands: "2", comment: "" },
          { addr: "106", op: "STORE_NAME", operands: "8 (t1)", comment: "" },
        ],
      },
      {
        label: "increment",
        instructions: [
          { addr: "0", op: "RESUME", operands: "0", comment: "" },
          { addr: "2", op: "LOAD_GLOBAL", operands: "1 (NULL + range)", comment: "" },
          { addr: "12", op: "LOAD_FAST", operands: "0 (n)", comment: "" },
          { addr: "14", op: "CALL", operands: "1", comment: "" },
          { addr: "22", op: "GET_ITER", operands: "", comment: "" },
          { addr: "28", op: "STORE_FAST", operands: "1 (i)", comment: "" },
          { addr: "30", op: "LOAD_GLOBAL", operands: "2 (lock)", comment: "" },
          { addr: "40", op: "LOAD_ATTR", operands: "5 (NULL|self + acquire)", comment: "" },
          { addr: "60", op: "CALL", operands: "0", comment: "" },
          { addr: "70", op: "LOAD_GLOBAL", operands: "6 (counter)", comment: "" },
          { addr: "80", op: "STORE_FAST", operands: "2 (temp)", comment: "" },
          { addr: "82", op: "LOAD_GLOBAL", operands: "9 (NULL + time)", comment: "" },
          { addr: "92", op: "LOAD_ATTR", operands: "10 (sleep)", comment: "" },
          { addr: "112", op: "LOAD_CONST", operands: "1 (0.001)", comment: "" },
          { addr: "114", op: "CALL", operands: "1", comment: "" },
          { addr: "124", op: "LOAD_FAST", operands: "2 (temp)", comment: "" },
          { addr: "126", op: "LOAD_CONST", operands: "2 (1)", comment: "" },
          { addr: "128", op: "BINARY_OP", operands: "0 (+)", comment: "" },
          { addr: "132", op: "STORE_GLOBAL", operands: "3 (counter)", comment: "" },
          { addr: "134", op: "LOAD_GLOBAL", operands: "2 (lock)", comment: "" },
          { addr: "144", op: "LOAD_ATTR", operands: "13 (NULL|self + release)", comment: "" },
          { addr: "164", op: "CALL", operands: "0", comment: "" },
          { addr: "174", op: "JUMP_BACKWARD", operands: "76 (to 24)", comment: "" },
          { addr: "178", op: "RETURN_CONST", operands: "0 (None)", comment: "" },
        ],
      },
      {
        label: "fast_sum",
        instructions: [
          { addr: "0", op: "RESUME", operands: "0", comment: "" },
          { addr: "2", op: "LOAD_GLOBAL", operands: "1 (NULL + sum)", comment: "" },
          { addr: "12", op: "LOAD_FAST", operands: "0 (data)", comment: "" },
          { addr: "14", op: "GET_ITER", operands: "", comment: "" },
          { addr: "16", op: "LOAD_FAST_AND_CLEAR", operands: "1 (x)", comment: "" },
          { addr: "20", op: "BUILD_LIST", operands: "0", comment: "" },
          { addr: "28", op: "STORE_FAST", operands: "1 (x)", comment: "" },
          { addr: "30", op: "LOAD_FAST", operands: "1 (x)", comment: "" },
          { addr: "32", op: "LOAD_CONST", operands: "1 (2)", comment: "" },
          { addr: "34", op: "BINARY_OP", operands: "5 (*)", comment: "" },
          { addr: "38", op: "LIST_APPEND", operands: "2", comment: "" },
          { addr: "40", op: "JUMP_BACKWARD", operands: "9 (to 24)", comment: "" },
          { addr: "48", op: "CALL", operands: "1", comment: "" },
          { addr: "56", op: "STORE_FAST", operands: "2 (result_comp)", comment: "" },
          { addr: "58", op: "LOAD_CONST", operands: "2 (0)", comment: "" },
          { addr: "60", op: "STORE_FAST", operands: "3 (result_loop)", comment: "" },
          { addr: "62", op: "LOAD_FAST", operands: "0 (data)", comment: "" },
          { addr: "64", op: "GET_ITER", operands: "", comment: "" },
          { addr: "72", op: "LOAD_FAST", operands: "3 (result_loop)", comment: "" },
          { addr: "74", op: "LOAD_FAST", operands: "1 (x)", comment: "" },
          { addr: "76", op: "LOAD_CONST", operands: "1 (2)", comment: "" },
          { addr: "78", op: "BINARY_OP", operands: "5 (*)", comment: "" },
          { addr: "82", op: "BINARY_OP", operands: "13 (+=)", comment: "" },
          { addr: "86", op: "STORE_FAST", operands: "3 (result_loop)", comment: "" },
          { addr: "92", op: "LOAD_FAST", operands: "2 (result_comp)", comment: "" },
          { addr: "94", op: "LOAD_FAST", operands: "3 (result_loop)", comment: "" },
          { addr: "96", op: "BUILD_TUPLE", operands: "2", comment: "" },
          { addr: "98", op: "RETURN_VALUE", operands: "", comment: "" },
        ],
      },
    ],
    notes: "Python bytecode via dis module.",
  },
  debugger: {
    steps: [
      { line: 1, description: "import threading", registers: {}, stack: ["<module>"] },
      { line: 2, description: "import time", registers: {}, stack: ["<module>"] },
      { line: 4, description: "Assign counter = 0", registers: { counter: "0" }, stack: ["<module>"] },
      { line: 5, description: "Assign lock = threading.Lock()", registers: { lock: "threading.Lock()", counter: "0" }, stack: ["<module>"] },
      { line: 23, description: "Assign t1 = threading.Thread(target=increment, args=...)", registers: { lock: "threading.Lock()", counter: "0", t1: "Thread(increment)" }, stack: ["<module>"] },
      { line: 24, description: "Assign t2 = threading.Thread(target=increment, args=...)", registers: { lock: "threading.Lock()", counter: "0", t1: "Thread(increment)", t2: "Thread(increment)" }, stack: ["<module>"] },
      { line: 25, description: "t1.start()", registers: { lock: "threading.Lock()", counter: "0", t1: "Thread(increment)", t2: "Thread(increment)" }, stack: ["<module>"] },
      { line: 26, description: "t2.start()", registers: { lock: "threading.Lock()", counter: "0", t1: "Thread(increment)", t2: "Thread(increment)" }, stack: ["<module>"] },
      { line: 27, description: "t1.join()", registers: { lock: "threading.Lock()", counter: "0", t1: "Thread(increment)", t2: "Thread(increment)" }, stack: ["<module>"] },
      { line: 28, description: "t2.join()", registers: { lock: "threading.Lock()", counter: "0", t1: "Thread(increment)", t2: "Thread(increment)" }, stack: ["<module>"] },
      { line: 29, description: "print(f\"Counter: {counter}\")", registers: { lock: "threading.Lock()", counter: "0", t1: "Thread(increment)", t2: "Thread(increment)" }, stack: ["<module>"] },
    ],
  },
  compare: {
    comparisons: [
      {
        title: "Manual lock.acquire/release vs with Statement",
        patterns: [
          {
            label: "Current: manual acquire/release",
            code: "lock.acquire()\ntry:\n    ...\nfinally:\n    lock.release()",
            cycles: "Same",
            memory: "Same",
            notes: "Risk of forgetting release on exception path",
          },
          {
            label: "Alternative: context manager",
            code: "with lock:\n    ...",
            cycles: "Same",
            memory: "Same",
            notes: "Exception-safe, guaranteed release",
          },
        ],
        winner: "Context manager \u2014 exception-safe, less error-prone",
      },
    ],
  },
};
